### ISSUE TITLE
Handle subsequent tweets with extra "replying to ..."

### ISSUE THREAD

**Issue by ftiasch** [ftiasch/sake#5]
A test case [Tweet 1](https://twitter.com/Misa2_omoshiroi/status/1315640781290397696) [Tweet 2](https://twitter.com/Misa2_omoshiroi/status/1315641076355530760)

`fetch_tweets(misa)[0..2]` yields
```
["Replying to\n          @Misa2_omoshiroi\n\n        \n        \n\n      \n\n    \n        #misa国午夜电台\n一帆风顺的我，没想到妈妈的反应会如此的夸张，夸张到她拿了一把刀好像真的要砍我一样。\n到底是不是真的？如果我不打飞那把刀，我会留下什么一生难忘的东西吗？\n那无所谓了。\n突然发现世界最亲的人失去了可以沟通的筹码，才是一切的开始。\n会发现自己越来越孤独。\n已经，十几年了呢。", "#misa国午夜电台\n抑郁。\n我的一切精神问题，源自那个有些冷的冬夜。\n那时，我是被宠坏的孩子，无论是家庭还是天赋，都是随心所欲的样子。\n不断的凭着天赋在探索着与我年龄严重不符的世界。\n至于为什么是性不是学术，为什么非要喜欢女人还会记录在手机上。\n我觉得，这只是一种冥冥之中的自然选择罢了。"]
```

A possible solution needs two adaptions. 

1. Change `last_tweet` from `String` to `[String]`.
2. Strip the extra `Replying to ...` off.

**Comment by zeyuwu** [comment]
Can we start using proper Twitter APIs for a change?

**Comment by ftiasch** [comment]
> Can we start using proper Twitter APIs for a change?

No, we can't. Even if switching to the official Twitter API, we still need to adapt the program logic to post multiple tweets at once. Also, I don't expect the API will alleviate the "replying to ..." problem, as it will come with some special fields or flags to indicate subsequent tweets which still needs to be handled. Meanwhile, the "Replying to ..." leader is sufficiently easy to deal with.
